name: Live Data Feed CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
      ImageOS: ubuntu22

    steps:
    - uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21
      with:
        elixir-version: '1.15.2'
        otp-version: '26.0'

    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Save Elixir and Erlang version for PLT caching
      run: echo "$ELIXIR_VERSION $ERLANG_VERSION" > .elixir_otp_version

    - name: Restore PLT cache
      uses: actions/cache@v3
      with:
        path: priv/plts
        key: plt-${{ runner.arch }}-${{ hashFiles('.elixir_otp_version', 'mix.lock') }}
        restore-keys: plt-${{ runner.arch }}-

    - name: Create PLTs
      run: mix dialyzer --plt

    - name: Save PLT cache
      uses: actions/cache@v3
      with:
        path: priv/plts
        key: plt-${{ runner.arch }}-${{ hashFiles('.elixir_otp_version', 'mix.lock') }}

    - name: Run dialyzer
      run: mix dialyzer

    - name: Run tests and coverage
      run: mix coveralls
